### PR TITLE
Support for data() method call for C++11 and after

### PR DESCRIPTION
**Pull request by rishitc**
To get a pointer to the first element of the underlying array used by the _vector_, C++11 and beyond, provides the ```data()``` method. 
Support for this call has been added with suitable preprocessor checks for the C++ standard used during compilation.

### CODE REVIEW

**Comment by rishitc** [comment]
I made the recommended changes but the tests still failed. I then even tried merging the ```&*begin()``` calls to ```data()```.
The vector class on compiling locally on my system, gave no errors.

Any inputs of why the tests failed would be really helpful!

I did check CircleCI, but the error messages reported are not useful. The website also says _some changes need to be made to the config file to save the test results._

Thanks.

**Comment by rishitc** [comment]
I'm extremely sorry for opening a new pull request. I'll close the old one and we can continue further discussions in this thread.

**Comment by kevina** [comment]
> I'm extremely sorry for opening a new pull request. I'll close the old one and we can continue further discussions in this thread.

Please don't.  Opening a new pull request was the correct thing to do.

**Comment by kevina** [comment]
>>  I'm extremely sorry for opening a new pull request. I'll close the old one and we can continue further discussions in this thread.

> Please don't. Opening a new pull request was the correct thing to do.

Oops.  Sorry.  I wasn't following what was going on.

Please do close this one.

**Pull request closed without merging**
