### PR TITLE
Markdown filter

### LINKED ISSUE #536: Please support markdown
Please support markdown as a known language.  Yeah, there are a lot of dialects.  I'm primarily interested in it ignoring  stuff inside ``` code fences ```

### PR DESCRIPTION
**Pull request by kevina**
Todo:
- [x] Document new filter in manual
- [x] Rebase to clean up commits
- [x] Check in test script

Closes #536.

Use `aspell --mode=markdown` to use.

To see what is being ignored use `aspell filter --mode=markdown`.

### CODE REVIEW

**Comment by kevina** [comment]
@RobertHenry6bev @hrabbey could you test this out and let me know if it works for you.

Please make sure you follow the instructions in the `README.md` or order to correctly compile from a git checkout.  (There is a README also, but that is intended for compiling from a tarball, so please ignore it).

**Comment by hrabbey** [comment]
Looks good.  

Thanks much.  It is a helpful improvement, meeting the original request for skipping code blocks / fences, and also URLs, and backtick quoted phrases nicely.

As expected, it does not seem to skip some other features of markdown.
One in particular that shows up for my usage is relative links for images.  For example, it would be great to ignore inside ]( ) below the same as a URL:


For a sample file, I used a couple of my own, and 
https://raw.githubusercontent.com/tchapi/markdown-cheatsheet/master/README.md
as well as
https://raw.githubusercontent.com/theno/revealjs_template/master/slides.md


I think it is a worthwhile improvement, but I want to emphasize for others that it is only very partially effective.  It would not make sense to embed a full parser.  Much better to let a user use the markdown parser of their choice, and / or pandoc, to convert to text for elaborate spell checking.
This may be worth mentioning when / if this feature gets documented.

However, for short, simple markdown tags, I think this improvement to aspell will be appreciated by others.  It is by me.

**Comment by kevina** [comment]
> it would be great to ignore inside ]( ) below the same as a URL:

That should be doable.  (BTW, the URL's are removed by the `url` filter which is ran after the markdown filter.)

>  It would not make sense to embed a full parser. Much better to let a user use the markdown parser of their choice, and / or pandoc, to convert to text for elaborate spell checking.

Unfortunately, that probably won't work well with the exiting filter framework.  Aspell needs to be able to determine where the word is in the document in order to be able to replace the word with the correct spelling.  Filters basically work by simply replacing stuff that should not be spell checked with spaces so that text remains aligned.

If you just want to check a document and list misspelling you can use pandoc to convert the document to HTML and then pipe the output through `aspell list --mode=html --add-html-skip=code`.  The output will be a list of misspellings.

**Comment by kevina** [comment]
@hrabbey `]( )` are now ignored so are link references so that `[link][ref]` will become `[link][   ]` and
```
[ref]: #c2 "Chapter 2"
```
will become
```
[   ]:    "Chapter 2"
```
but this can be turned off with `--dont-markdown-skip-ref-labels`.

**Comment by zerok** [comment]
Sorry for the late response 😭 Thank you for working on this 😍

**Comment by kevina** [comment]
A pre-release snapshot is now available with the new Markdown filter: https://github.com/GNUAspell/aspell/releases/tag/rel-0.60.8-20190817 if anyone wants to try it out and didn't want to use the git version.

**Pull request merged**
