### PR TITLE
Fix a typo and some other minor tweaks

### PR DESCRIPTION
**Pull request by peternewman**
Mostly Sourceforge to GitHub

### CODE REVIEW

**Comment by peternewman** [comment]
AppVeyor seems to be failing due to a config issue rather than my changes as far as I can see.

**Comment by kevina** [comment]
Thanks for catching this.  I do admit that I don't spell check every single string in the source code, but I am not sure how this got though.  Can you please remove "the irony" from the commit message.  If you want to rebase everything into a single commit that fine.

**Comment by kevina** [comment]
> AppVeyor seems to be failing due to a config issue rather than my changes as far as I can see.

Yeah it's not really set up, so don't worry about it.  Sorry for the trouble.

**Comment by peternewman** [comment]
> Thanks for catching this. I do admit that I don't spell check every single string in the source code, but I am not sure how this got though.

I could setup codespell to via Travis (which I've now added this particular typo to it's dictionary; it didn't have it either), or is that being too cheeky?

> Can you please remove "the irony" from the commit message. If you want to squash everything into a single commit that fine.

I've done these all via the web UI and there's no magic button for me to do that on there. I think there might be an option when you're merging in GitHub? Otherwise I never seem to have much luck with squashing and rebasing etc and find it takes me about three goes.

**Comment by peternewman** [comment]
> > AppVeyor seems to be failing due to a config issue rather than my changes as far as I can see.
> 
> Yeah it's not really set up, so don't worry about it. Sorry for the trouble.

Travis probably wouldn't be too hard if that's of interest?

**Comment by kevina** [comment]
>> Can you please remove "the irony" from the commit message. If you want to squash everything into a single commit that fine.

> I've done these all via the web UI and there's no magic button for me to do that on there. I think there might be an option when you're merging in GitHub? Otherwise I never seem to have much luck with squashing and rebasing etc and find it takes me about three goes.

Okay I do it for you then.

**Comment by kevina** [comment]
> Travis probably wouldn't be too hard if that's of interest?

Not right now.  I have CircleCI setup up, and might setup Travis myself at a later date.

But thanks for the offer.

**Comment by peternewman** [comment]
> Okay I do it for you then.

Thanks @kevina 

> Not right now. I have CircleCI setup up, and might setup Travis myself at a later date.
> 
> But thanks for the offer.

Ah, any reason you don't have the GitHub integration? I missed the config folder as I only saw the AppVeyor check status.

**Comment by kevina** [comment]
> Ah, any reason you don't have the GitHub integration? I missed the config folder as I only saw the AppVeyor check status.

It should be enabled see https://github.com/GNUAspell/aspell/commits/master and click on the green check mark or red x.  I might not have something configured right but have not had time to investigate.

**Comment by kevina** [comment]
Thanks.  I rebased and merged in #554.

**Comment by peternewman** [comment]
> > Ah, any reason you don't have the GitHub integration? I missed the config folder as I only saw the AppVeyor check status.
> 
> It should be enabled see https://github.com/GNUAspell/aspell/commits/master and click on the green check mark or red x. I might not have something configured right but have not had time to investigate.

I was expecting to see them in my PR, but I could only see the failing AppVeyor one, a bit of Googling reveals that I think this is what's missing (the equivalent is enabled by default in Travis which was confusing me):
https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories

**Comment by kevina** [comment]
> I was expecting to see them in my PR, but I could only see the failing AppVeyor one, a bit of Googling reveals that I think this is what's missing 

Thanks for finding that setting.  That setting is enabled now.

**Pull request closed without merging**
